/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export type Language = { 'danish' : null } |
  { 'turkish' : null } |
  { 'spanish' : null } |
  { 'bulgarian' : null } |
  { 'english' : null };
export interface Newsletter {
  'id' : bigint,
  'pdf' : [] | [ExternalBlob],
  'status' : string,
  'title' : string,
  'description' : string,
  'publicationDate' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addNewsletter' : ActorMethod<
    [bigint, string, string, string, string, [] | [ExternalBlob]],
    undefined
  >,
  'addTranslation' : ActorMethod<[Language, string, string], undefined>,
  'correctNewsletter1PublicationDate' : ActorMethod<[], undefined>,
  'getAllNewsletters' : ActorMethod<[], Array<Newsletter>>,
  'getAvailableLanguages' : ActorMethod<[], Array<Language>>,
  'getNewsletter' : ActorMethod<[bigint], Newsletter>,
  'getPDF' : ActorMethod<[bigint], [] | [ExternalBlob]>,
  'getTranslation' : ActorMethod<[Language, string], string>,
  'updateNewsletterPDF' : ActorMethod<[bigint, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];