/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Language = IDL.Variant({
  'danish' : IDL.Null,
  'turkish' : IDL.Null,
  'spanish' : IDL.Null,
  'bulgarian' : IDL.Null,
  'english' : IDL.Null,
});
export const Newsletter = IDL.Record({
  'id' : IDL.Nat,
  'pdf' : IDL.Opt(ExternalBlob),
  'status' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'publicationDate' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addNewsletter' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'addTranslation' : IDL.Func([Language, IDL.Text, IDL.Text], [], []),
  'correctNewsletter1PublicationDate' : IDL.Func([], [], []),
  'getAllNewsletters' : IDL.Func([], [IDL.Vec(Newsletter)], ['query']),
  'getAvailableLanguages' : IDL.Func([], [IDL.Vec(Language)], ['query']),
  'getNewsletter' : IDL.Func([IDL.Nat], [Newsletter], ['query']),
  'getPDF' : IDL.Func([IDL.Nat], [IDL.Opt(ExternalBlob)], ['query']),
  'getTranslation' : IDL.Func([Language, IDL.Text], [IDL.Text], ['query']),
  'updateNewsletterPDF' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Language = IDL.Variant({
    'danish' : IDL.Null,
    'turkish' : IDL.Null,
    'spanish' : IDL.Null,
    'bulgarian' : IDL.Null,
    'english' : IDL.Null,
  });
  const Newsletter = IDL.Record({
    'id' : IDL.Nat,
    'pdf' : IDL.Opt(ExternalBlob),
    'status' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'publicationDate' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addNewsletter' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'addTranslation' : IDL.Func([Language, IDL.Text, IDL.Text], [], []),
    'correctNewsletter1PublicationDate' : IDL.Func([], [], []),
    'getAllNewsletters' : IDL.Func([], [IDL.Vec(Newsletter)], ['query']),
    'getAvailableLanguages' : IDL.Func([], [IDL.Vec(Language)], ['query']),
    'getNewsletter' : IDL.Func([IDL.Nat], [Newsletter], ['query']),
    'getPDF' : IDL.Func([IDL.Nat], [IDL.Opt(ExternalBlob)], ['query']),
    'getTranslation' : IDL.Func([Language, IDL.Text], [IDL.Text], ['query']),
    'updateNewsletterPDF' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };